"""Criação inicial das tabelas

Revision ID: 05ee030e79ae
Revises: 57659ae7b8cd
Create Date: 2025-03-06 16:07:56.993608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ee030e79ae'
down_revision = '57659ae7b8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nivel_senioridade', sa.String(length=50), nullable=False),
    sa.Column('custo_por_hora', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('status_tarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('horas_fechadas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim_previsto', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('total_horas_estimadas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_tarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('status_tarefa_id', sa.Integer(), nullable=False),
    sa.Column('servico_projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['servico_projeto_id'], ['servico_projeto.id'], ),
    sa.ForeignKeyConstraint(['status_tarefa_id'], ['status_tarefa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('horas_estimadas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('horas_gastas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('status_tarefa_id', sa.Integer(), nullable=False),
    sa.Column('servico_projeto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_tarefa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['servico_projeto_id'], ['servico_projeto.id'], ),
    sa.ForeignKeyConstraint(['status_tarefa_id'], ['status_tarefa.id'], ),
    sa.ForeignKeyConstraint(['tipo_tarefa_id'], ['tipo_tarefa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apontamento_horas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('horas_trabalhadas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamento_horas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tarefa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], ),
    sa.ForeignKeyConstraint(['tipo_tarefa_id'], ['tipo_tarefa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamento_horas')
    op.drop_table('apontamento_horas')
    op.drop_table('tarefa')
    op.drop_table('tipo_tarefa')
    op.drop_table('servico_projeto')
    op.drop_table('projeto')
    op.drop_table('tipo_servico')
    op.drop_table('status_tarefa')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
