"""Adicionando chave estrangeira para TipoTarefa em LancamentoHoras

Revision ID: 0bc6b941ac08
Revises: 
Create Date: 2025-02-20 16:07:45.632959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc6b941ac08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_horas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TipoTarefa_ID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_tipo_tarefa_id', 'tipo_tarefa', ['TipoTarefa_ID'], ['TipoTarefa_ID'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_horas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tipo_tarefa_id', type_='foreignkey')
        batch_op.drop_column('TipoTarefa_ID')

    # ### end Alembic commands ###
