"""Descrição da migração

Revision ID: 57659ae7b8cd
Revises: d9a6fef83d76
Create Date: 2025-03-06 09:14:54.222174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57659ae7b8cd'
down_revision = 'd9a6fef83d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamento_horas', sa.Column('tipo_tarefa_id', sa.Integer(), nullable=False))
    op.alter_column('lancamento_horas', 'horas',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'lancamento_horas', 'tipo_tarefa', ['tipo_tarefa_id'], ['id'])
    op.add_column('pessoa', sa.Column('perfil', sa.String(length=50), nullable=False))
    op.alter_column('pessoa', 'custo_por_hora',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.drop_column('pessoa', 'senha')
    op.alter_column('projeto', 'nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('projeto', 'descricao',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('projeto', 'total_horas_estimadas',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('servico_projeto', 'descricao',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('status_tarefa', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('status_tarefa', sa.Column('titulo', sa.String(length=100), nullable=False))
    op.drop_column('status_tarefa', 'StatusTarefa_ID')
    op.drop_column('status_tarefa', 'StatusTarefa_Nome')
    op.add_column('tarefa', sa.Column('status_tarefa_id', sa.Integer(), nullable=False))
    op.add_column('tarefa', sa.Column('servico_projeto_id', sa.Integer(), nullable=True))
    op.add_column('tarefa', sa.Column('tipo_tarefa_id', sa.Integer(), nullable=False))
    op.alter_column('tarefa', 'titulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tarefa', 'descricao',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('tarefa', 'horas_estimadas',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('tarefa', 'horas_gastas',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=False)
    op.alter_column('tarefa', 'data_fim',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'tarefa', 'status_tarefa', ['status_tarefa_id'], ['id'])
    op.create_foreign_key(None, 'tarefa', 'servico_projeto', ['servico_projeto_id'], ['id'])
    op.create_foreign_key(None, 'tarefa', 'tipo_tarefa', ['tipo_tarefa_id'], ['id'])
    op.alter_column('tipo_servico', 'horas_fechadas',
               existing_type=sa.BOOLEAN(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.add_column('tipo_tarefa', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('tipo_tarefa', sa.Column('nome', sa.String(length=100), nullable=False))
    op.add_column('tipo_tarefa', sa.Column('pessoa_id', sa.Integer(), nullable=False))
    op.add_column('tipo_tarefa', sa.Column('status_tarefa_id', sa.Integer(), nullable=False))
    op.add_column('tipo_tarefa', sa.Column('servico_projeto_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'tipo_tarefa', type_='foreignkey')
    op.drop_constraint(None, 'tipo_tarefa', type_='foreignkey')
    op.drop_constraint(None, 'tipo_tarefa', type_='foreignkey')
    op.create_foreign_key(None, 'tipo_tarefa', 'servico_projeto', ['servico_projeto_id'], ['id'])
    op.create_foreign_key(None, 'tipo_tarefa', 'pessoa', ['pessoa_id'], ['id'])
    op.create_foreign_key(None, 'tipo_tarefa', 'status_tarefa', ['status_tarefa_id'], ['id'])
    op.drop_column('tipo_tarefa', 'ServicoProjeto_ID')
    op.drop_column('tipo_tarefa', 'StatusTarefa_ID')
    op.drop_column('tipo_tarefa', 'Pessoa_ID')
    op.drop_column('tipo_tarefa', 'TipoTarefa_Nome')
    op.drop_column('tipo_tarefa', 'TipoTarefa_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_tarefa', sa.Column('TipoTarefa_ID', sa.INTEGER(), nullable=False))
    op.add_column('tipo_tarefa', sa.Column('TipoTarefa_Nome', sa.VARCHAR(length=100), nullable=False))
    op.add_column('tipo_tarefa', sa.Column('Pessoa_ID', sa.INTEGER(), nullable=False))
    op.add_column('tipo_tarefa', sa.Column('StatusTarefa_ID', sa.INTEGER(), nullable=False))
    op.add_column('tipo_tarefa', sa.Column('ServicoProjeto_ID', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'tipo_tarefa', type_='foreignkey')
    op.drop_constraint(None, 'tipo_tarefa', type_='foreignkey')
    op.drop_constraint(None, 'tipo_tarefa', type_='foreignkey')
    op.create_foreign_key(None, 'tipo_tarefa', 'status_tarefa', ['StatusTarefa_ID'], ['StatusTarefa_ID'])
    op.create_foreign_key(None, 'tipo_tarefa', 'servico_projeto', ['ServicoProjeto_ID'], ['id'])
    op.create_foreign_key(None, 'tipo_tarefa', 'pessoa', ['Pessoa_ID'], ['id'])
    op.drop_column('tipo_tarefa', 'servico_projeto_id')
    op.drop_column('tipo_tarefa', 'status_tarefa_id')
    op.drop_column('tipo_tarefa', 'pessoa_id')
    op.drop_column('tipo_tarefa', 'nome')
    op.drop_column('tipo_tarefa', 'id')
    op.alter_column('tipo_servico', 'horas_fechadas',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_constraint(None, 'tarefa', type_='foreignkey')
    op.drop_constraint(None, 'tarefa', type_='foreignkey')
    op.drop_constraint(None, 'tarefa', type_='foreignkey')
    op.alter_column('tarefa', 'data_fim',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tarefa', 'horas_gastas',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('tarefa', 'horas_estimadas',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('tarefa', 'descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('tarefa', 'titulo',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('tarefa', 'tipo_tarefa_id')
    op.drop_column('tarefa', 'servico_projeto_id')
    op.drop_column('tarefa', 'status_tarefa_id')
    op.add_column('status_tarefa', sa.Column('StatusTarefa_Nome', sa.VARCHAR(length=100), nullable=False))
    op.add_column('status_tarefa', sa.Column('StatusTarefa_ID', sa.INTEGER(), nullable=False))
    op.drop_column('status_tarefa', 'titulo')
    op.drop_column('status_tarefa', 'id')
    op.alter_column('servico_projeto', 'descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('projeto', 'total_horas_estimadas',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('projeto', 'descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('projeto', 'nome',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('pessoa', sa.Column('senha', sa.VARCHAR(length=100), nullable=False))
    op.alter_column('pessoa', 'custo_por_hora',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('pessoa', 'perfil')
    op.drop_constraint(None, 'lancamento_horas', type_='foreignkey')
    op.alter_column('lancamento_horas', 'horas',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('lancamento_horas', 'tipo_tarefa_id')
    # ### end Alembic commands ###
