"""Adicionando campo senha na tabela Pessoa

Revision ID: 7ab1c6734edb
Revises: 05ee030e79ae
Create Date: 2025-03-06 17:02:39.608965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab1c6734edb'
down_revision = '05ee030e79ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('senha', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa', 'senha')
    # ### end Alembic commands ###
