"""Adicionando campo senha na tabela Pessoa

Revision ID: c080d1b9ef61
Revises: 7ab1c6734edb
Create Date: 2025-03-07 09:54:47.190990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c080d1b9ef61'
down_revision = '7ab1c6734edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
